eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application :
    name: COMPANY-SERVICE
  data:
    mongodb:
      database: management_system
      host: localhost
      port: 27017
  kafka:
    consumer:
      bootstarp-servers: localhost:9092
      group-id: "my_group_id"
      auto-offset-reset: earliest #to define the behavior of the consumer when there is no committed position!
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
